before_install:
  - git submodule update --init --recursive


before_script:
  - sh -e /etc/init.d/xvfb start

language: python
python:
  - 2.6
  - 2.7

script: py.test --baseurl=http://dev.openbadges.org/ --driver=firefox -m "not credentials" --destructive


env:
  - DISPLAY=':99.0'


notifications:
  email:
    - bebe@mozilla.ro